-- ORDER_ITEMS
-- Stores line-level order details including products, quantities,
-- pricing, and sales values for detailed revenue analysis.


CREATE TABLE APPUSER.ORDER_ITEMS
(
  ORDERNO          NUMBER,
  ORDERLINENUMBER  NUMBER,
  PRODUCTCODE      VARCHAR2(50 BYTE),
  QUANTITYORDERED  NUMBER,
  PRICEEACH        NUMBER(10,2),
  SALES            NUMBER(12,2)
)
TABLESPACE USERS
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX APPUSER.PK_ORDER_ITEMS ON APPUSER.ORDER_ITEMS
(ORDERNO, ORDERLINENUMBER)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE APPUSER.ORDER_ITEMS ADD (
  CONSTRAINT PK_ORDER_ITEMS
  PRIMARY KEY
  (ORDERNO, ORDERLINENUMBER)
  USING INDEX APPUSER.PK_ORDER_ITEMS
  ENABLE VALIDATE);


ALTER TABLE APPUSER.ORDER_ITEMS ADD (
  FOREIGN KEY (ORDERNO) 
  REFERENCES APPUSER.ORDERS (ORDERNO)
  ENABLE VALIDATE);
